#spring和druid连接池配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
# 配置系统类型
system:
  type: windows
  domain: http://localhost:9091
  file-load: blog-api
  file-cate: img
  file-save: \\api\\src\\main\\resources\\static\\img

# sql 打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl