#spring和druid连接池配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.94.228.123:3306/blog01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
# 配置系统类型
system:
  type: linux
  domain:  https://fhs.faig.top
  # 图片上传项目位置
  file-load: dist
  file-cate: img
  file-save: /www/server/tomcat/webapps/dist/img